Repository ourchitecture/hello-cloud, pull requests merged in 2021-12, with the labels that each got.

#63 docs: mermaid diagrams
  .prettierignore
  makefile
  mkdocs.yml
  src/docs/assets/stylesheets/extra.css
  src/docs/contribute.md
  src/docs/index.md
  src/docs/license.md
  src/docs/roadmap.md
  src/docs/services/java-springboot.md
  src/docs/services/kotlin-springboot.md
  src/mkdocs/Dockerfile
  src/mkdocs/overrides/main.html
Labels: documentation, enhancement

#65 docs: diagrams
  mkdocs.yml
  src/docs/assets/stylesheets/extra.css
  src/docs/contribute.md
  src/docs/index.md
Labels: documentation, enhancement

#67 fix: diagram labels
  src/docs/assets/stylesheets/extra.css
Labels: bug, documentation

#70 chore: remove older and unused mkdocs-mermaid2-plugin
  mkdocs.yml
  src/docs/assets/stylesheets/extra.css
  src/mkdocs/Dockerfile
Labels: documentation

#72 docs: heroku abstractions
  src/docs/index.md
Labels: documentation, enhancement

#74 docs: devops status badges
  src/docs/devops.md
Labels: documentation, enhancement

#76 docs: update open source links
  src/docs/contribute.md
  src/docs/license.md
Labels: documentation, enhancement

#78 docs: docker open source
  src/docs/license.md
Labels: documentation, enhancement

#80 fix: dotnet workflow file name
  src/docs/services/dotnet.md
Labels: bug, documentation

#103 chore: refactor nodejs heroku and multi-cloud
  .github/workflows/docker_heroku-cli.yml
  src/docker/heroku-cli/Dockerfile
  src/docker/heroku-cli/makefile
  src/docs/clouds.md
  src/docs/services/nodejs-expressjs.md
  src/services/nodejs/expressjs/webapi/deploy/azure/uninstall.sh
  src/services/nodejs/expressjs/webapi/deploy/gcloud/.env.example
  src/services/nodejs/expressjs/webapi/deploy/gcloud/logs.sh
  src/services/nodejs/expressjs/webapi/deploy/gcloud/uninstall
  src/services/nodejs/expressjs/webapi/deploy/heroku/.env.example
  src/services/nodejs/expressjs/webapi/deploy/heroku/install.sh
  src/services/nodejs/expressjs/webapi/deploy/heroku/login.sh
  src/services/nodejs/expressjs/webapi/deploy/heroku/logs.sh
  src/services/nodejs/expressjs/webapi/deploy/heroku/makefile
  src/services/nodejs/expressjs/webapi/deploy/heroku/uninstall
  src/services/nodejs/expressjs/webapi/makefile
Labels: documentation, enhancement

#106 test: nodejs dev tool tasks
  src/services/nodejs/expressjs/webapi/.dockerignore
  src/services/nodejs/expressjs/webapi/deploy/heroku/makefile
  src/services/nodejs/expressjs/webapi/docker/Dockerfile
  src/services/nodejs/expressjs/webapi/docker/docker-compose.yml
  src/services/nodejs/expressjs/webapi/makefile
  src/services/nodejs/expressjs/webapi/test-local-tools.sh
Labels: enhancement

#107 Updated './src/docs/assets/stylesheets/extra.css' and './src/docs/contribute.md' files
  src/docs/assets/stylesheets/extra.css
  src/docs/contribute.md
Labels: documentation, enhancement

#114 docs: cloud links and diagrams
  makefile
  src/docs/assets/images/diagrams/bmc-cloud-comparison.jpg
  src/docs/assets/images/diagrams/cloud-computing-abstractions.png
  src/docs/clouds.md
  src/media/diagrams/cloud-computing-abstractions/cloud-computing-abstractions.drawio
Labels: documentation, enhancement

#121 docs: compute packages
  src/docs/assets/images/diagrams/computing-abstraction-packages.png
  src/docs/clouds.md
  src/media/diagrams/cloud-computing-packages/computing-abstraction-packages.drawio
Labels: documentation, enhancement

#123 docs: several improvement commits
  .github/workflows/documentation.yml
  .vscode/extensions.json
  src/docs/assets/images/diagrams/computing-abstraction-packages.png
  src/docs/clouds.md
  src/docs/img/favicon.png
  src/docs/img/logo.png
  src/docs/index.md
  src/docs/license.md
  src/docs/services/dotnet.md
  src/docs/services/java-springboot.md
  src/docs/services/kotlin-springboot.md
  src/docs/services/nodejs-expressjs.md
  src/media/diagrams/cloud-computing-packages/computing-abstraction-packages.drawio
  src/services/jvm/java/springboot/webapi/azure-init.sh
  src/services/jvm/kotlin/springboot/webapi/azure-init.sh
  src/services/nodejs/expressjs/webapi/deploy/aws/makefile
  src/services/nodejs/expressjs/webapi/deploy/aws/uninstall.sh
  src/services/nodejs/expressjs/webapi/deploy/azure/install.sh
  src/services/nodejs/expressjs/webapi/deploy/azure/uninstall.sh
Labels: documentation, enhancement

#124 ci: fix github event name
  .github/workflows/documentation.yml
Labels: bug

#125 ci: revert condition to push only
  .github/workflows/documentation.yml
Labels: bug

#127 feat: app manifest
  mkdocs.yml
  src/docs/assets/images/hello-cloud_192x192.png
  src/docs/assets/images/hello-cloud_512x512.png
  src/docs/assets/scripts/extra.js
  src/docs/assets/stylesheets/extra.css
  src/docs/manifest.webmanifest
  src/mkdocs/overrides/main.html
Labels: documentation, enhancement

#129 fix: relative start_url in manifest
  src/docs/manifest.webmanifest
Labels: bug

#131 fix: manifest
  src/docs/assets/scripts/extra.js
  src/docs/manifest.webmanifest
Labels: bug

#133 fix: hard-code manifest start_url
  src/docs/manifest.webmanifest
Labels: bug

#135 chore: update google analytics code
  mkdocs.yml
  src/docs/index.md
Labels: enhancement

#137 chore: deprecate custom mkdocs docker image
  makefile
  src/mkdocs/Dockerfile
  src/mkdocs/makefile
Labels: enhancement

#139 feat: make check-versions
  check-versions.sh
  makefile
  src/docker/aws-cli/Dockerfile
  src/docker/aws-cli/check-versions.sh
  src/docker/aws-cli/makefile
  src/docker/azure-cli/Dockerfile
  src/docker/azure-cli/check-versions.sh
  src/docker/azure-cli/makefile
  src/docker/heroku-cli/check-versions.sh
  src/docker/heroku-cli/makefile
  src/services/dotnet/webapi/check-versions.sh
  src/services/dotnet/webapi/makefile
  src/services/jvm/java/springboot/webapi/build.gradle
  src/services/jvm/java/springboot/webapi/check-versions.sh
  src/services/jvm/java/springboot/webapi/makefile
  src/services/jvm/java/springboot/webapi/pom.xml
  src/services/jvm/kotlin/springboot/webapi/check-versions.sh
  src/services/jvm/kotlin/springboot/webapi/makefile
  src/services/nodejs/expressjs/webapi/check-versions.sh
  src/services/nodejs/expressjs/webapi/makefile
Labels: enhancement

#146 docs: maintainers
  src/docs/contribute.md
Labels: documentation, enhancement
