Repository ourchitecture/hello-cloud, pull requests merged in 2022-01, with the labels that each got.

#153 feat(docker/aws-cli): yum-utils
  src/docker/aws-cli/Dockerfile
  src/docker/aws-cli/makefile
Labels: enhancement

#156 feat: dockerize dotnet deployment to azure
  src/docs/clouds.md
  src/docs/services/dotnet.md
  src/services/dotnet/webapi/.azure/config
  src/services/dotnet/webapi/deploy/azure/.env.example
  src/services/dotnet/webapi/deploy/azure/install.sh
  src/services/dotnet/webapi/deploy/azure/makefile
  src/services/dotnet/webapi/makefile
  src/services/nodejs/expressjs/webapi/deploy/azure/.env.example
  src/services/nodejs/expressjs/webapi/deploy/azure/install.sh
Labels: enhancement

#158 fix: missing dotnet azure cloud headline
  makefile
  src/docs/services/dotnet.md
Labels: bug, documentation

#160 feat: dockerize dotnet deployment to gcloud
  makefile
  src/docs/index.md
  src/docs/services/dotnet.md
  src/docs/services/java-springboot.md
  src/docs/services/kotlin-springboot.md
  src/docs/services/nodejs-expressjs.md
  src/services/dotnet/webapi/.gcloudignore
  src/services/dotnet/webapi/Dockerfile
  src/services/dotnet/webapi/Program.cs
  src/services/dotnet/webapi/check-versions.sh
  src/services/dotnet/webapi/deploy/azure/.env.example
  src/services/dotnet/webapi/deploy/gcloud/.env.example
  src/services/dotnet/webapi/deploy/gcloud/install.sh
  src/services/dotnet/webapi/deploy/gcloud/makefile
  src/services/dotnet/webapi/gcloud-app.yaml
  src/services/dotnet/webapi/gcloud-init.sh
  src/services/dotnet/webapi/makefile
  src/services/nodejs/expressjs/webapi/deploy/azure/.env.example
  src/services/nodejs/expressjs/webapi/deploy/gcloud/.env.example
  src/services/nodejs/expressjs/webapi/deploy/gcloud/install.sh
  src/services/nodejs/expressjs/webapi/deploy/gcloud/logs.sh
Labels: enhancement

#162 feat: dockerize dotnet deploy to heroku
  src/docs/clouds.md
  src/docs/services/dotnet.md
  src/services/dotnet/webapi/deploy/gcloud/makefile
  src/services/dotnet/webapi/deploy/heroku/install.sh
  src/services/dotnet/webapi/deploy/heroku/makefile
  src/services/dotnet/webapi/makefile
  src/services/nodejs/expressjs/webapi/deploy/gcloud/makefile
  src/services/nodejs/expressjs/webapi/deploy/heroku/makefile
Labels: documentation, enhancement

#164 fix: do not run documentation pr for forks
  .github/workflows/documentation.yml
Labels: bug

#165 fix: documentation pr
  .github/workflows/documentation.yml
Labels: bug

#166 test: pr vs push event info
  .github/workflows/documentation.yml
Labels: bug

#168 fix: do not generate auto-doc pr for forks
  .github/workflows/documentation.yml
Labels: bug

#170 chore: refactor strings as vars
  .github/workflows/documentation.yml
Labels: documentation

#171 fix: repo comparison
  .github/workflows/documentation.yml
Labels: bug

#175 feat: automate documentation screenshots
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/documentation.yml
  .gitignore
  makefile
  src/docker/puppeteer/.gitignore
  src/docker/puppeteer/Dockerfile
  src/docker/puppeteer/entrypoint.sh
  src/docker/puppeteer/makefile
  src/docker/puppeteer/test.js
  src/docs/devops.md
  src/puppeteer/.gitignore
  src/puppeteer/makefile
  src/puppeteer/screenshots.js
  src/puppeteer/start.sh
Labels: enhancement

#177 chore: replace individuals with teams
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/documentation.yml
Labels: enhancement

#179 fix: use @mention format for reviewer team
  .github/workflows/documentation.yml
Labels: bug

#183 test: directly assign team as reviewer
  .github/workflows/documentation.yml
Labels: bug

#187 chore: pr assignee
  .github/workflows/documentation.yml
Labels: enhancement

#189 fix: pr mention
  .github/workflows/documentation.yml
Labels: bug

#191 fix: pr mention
  .github/workflows/documentation.yml
Labels: bug

#195 chore: use system account pat for team-reviewers
  .github/workflows/documentation.yml
Labels: bug

#196 docs: auto-generated documentation
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: documentation

#197 Pr system account
  .github/workflows/documentation.yml
Labels: bug

#198 docs: auto-generated documentation
  docs/sitemap.xml.gz
Labels: documentation

#199 docs: cloud comparisons
  .github/workflows/documentation.yml
  mkdocs.yml
  src/docs/clouds.md
  src/docs/compare.md
  src/docs/index.md
  src/puppeteer/screenshots.js
Labels: documentation, enhancement

#201 docs: multi-cloud
  src/docs/clouds.md
Labels: documentation

#202 docs: auto-generated documentation
  docs/clouds/index.html
  docs/search/search_index.json
  docs/sitemap.xml.gz
Labels: documentation

#204 feat: cli
  makefile
  node_modules/.yarn-integrity
  package.json
  src/cli/ourc/.circleci/config.yml
  src/cli/ourc/.editorconfig
  src/cli/ourc/.eslintignore
  src/cli/ourc/.eslintrc
  src/cli/ourc/.github/dependabot.yml
  src/cli/ourc/.gitignore
  src/cli/ourc/.mocharc.json
  src/cli/ourc/LICENSE
  src/cli/ourc/README.md
  src/cli/ourc/bin/dev
  src/cli/ourc/bin/dev.cmd
  src/cli/ourc/bin/run
  src/cli/ourc/bin/run.cmd
  src/cli/ourc/package.json
  src/cli/ourc/src/commands/git/index.ts
  src/cli/ourc/src/commands/git/main.ts
  src/cli/ourc/src/commands/git/pr.ts
  src/cli/ourc/src/commands/git/sync.ts
  src/cli/ourc/src/commands/hello/index.ts
  src/cli/ourc/src/commands/hello/world.ts
  src/cli/ourc/src/index.ts
  src/cli/ourc/test/commands/hello/index.test.ts
  src/cli/ourc/test/commands/hello/world.test.ts
  src/cli/ourc/test/helpers/init.js
  src/cli/ourc/test/tsconfig.json
  src/cli/ourc/tsconfig.json
  src/cli/ourc/yarn.lock
  yarn.lock
Labels: enhancement

#205 docs: auto-generated documentation
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: documentation
